README.md
https://github.com/rust-analyzer/rust-analyzer updated their installation instructions to:
```
$ git clone https://github.com/rust-analyzer/rust-analyzer && cd rust-analyzer
$ cargo xtask install
$ cargo xtask install --server
```
=> Update README.md from install-ra to xtask

README.md
Hey, thanks for all the amazing work on this project. I just switched from coc-rls and coc-rust-analyzer seems to be working very well. 
I noticed this tiny typo in the in the README when I was looking for how to configure coc-rust-analyzer to run clippy.
=> Correct readme typo for cargo watch command config

package.json, src/config.ts, src/ctx.ts, src/downloader.ts, src/index.ts
Similar to the VS Code plugin, the `rust-analyzer.updates.channel` setting downloads nightly releases if set to `nightly`
Config name and documentation taken from `rust-analyzer`: https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/code/package.json#L342
=> Enable nightly channel config

src/client.ts, src/cmds/index.ts, src/index.ts, src/source_change.ts
https://github.com/rust-analyzer/rust-analyzer/pull/4494
@oblitum @TimoFreiberg can you guys test this? Maybe you need to download latest nightly release.
=> feat(cmds): support snippet text edit

package.json, src/commands.ts
Hi you folks have been doing awesome work with coc-rust-analyzer!
This pr enables the debug codelens action using the termdebug package from neovim.
I'm not very familiar with coc, so please let me know where the code can be improved and I will happily work on it.
This requires termdebug package:
```viml
packadd termdebug
let g:termdebugger="rust-gdb"
```
Btw this is heavily based on rust-analyzer for vscode.
=> Add debugSingle command - This enables codelens debug action

src/commands.ts
Lib crates have a slightly different json message in the output. This pr enables debugSingle to lib crates
=> Add support to debugSingle in lib crates

README.md, package.json, src/commands.ts, src/index.ts
This PR adds `rust-analyzer.explainError` as discussed in #467, which shows the output of `rustc --explain`, explaining the currently hovered error. It can both show it in a popup, as well as in a new buffer. This is configurable via `rust-analyzer.explainInPopup`.
Here's an example showing how it looks in the popup:
This is how it looks with `rust-analyzer.explainInPopup` set to false
=> feat: Add `rust-analyzer.explainError`

src/inlay_hints.ts
#394 
I made a small change to @the10thWiz's patch to also add the name of the symbol together with the type. The result will look like this:
IMO this makes it easier to associate the type to its symbol without having to go back and forth in the line. Let me know if that works.
=> Added logic to display symbol name together with its type

src/ctx.ts
Currently, setting `rust-analyzer.inlayHints.enable` to false will only disables initial activation, not completely disable inlay hints.
=> Fix inlayHints.enable option

README.md
add missing `rust-analyzer.completion.autoimport.enable` doc
=> add missing option doc

README.md, src/commands.ts, src/index.ts
Fixes #719 
Also added a similar `debug` command and refactored them to use `runSingle` and `debugSingle`. I wasn't able to access `debugSingle` because I think codelens only works on neovim. I assume the original `rust-analyzer.run` was intended as a workaround for vanilla vim users so I provided the same functionality for `rust-analyzer.debug`.
=> Include executable arguments when executing a runnable

src/client.ts, src/lsp_ext.ts
=> feat: range hover

package.json
`coc-rust-analyzer` relies on `coc` to find the correct WorkspaceFolder. The location [is based on](https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders) the `rootPatterns` provided by the plugin. Add `rust-project.json` to the pattern list.
Fixes: #917
=> Add rust-project.json to rootPatterns

src/commands.ts
First noticed in:
https://github.com/rust-lang/rust-analyzer/issues/11489
Where I saw that generics prevent a test case from running. It turns out
that the `<` and `>` made my shell I was redirecting to a file (I tested
this in other shells and got the same behavior). As such, I made a PR to
rust-analyzer, but it turns out that this is an "IDE" bug, as we
directly send the cmd to be run on the terminal.
To fix the issue, I simply surrounded the path with quotes.
=> Added single quotes around the executable path for Terminal Runnables

README.md
Hi!
I tried setting my rust-analyzer inlay hints to work for "all features" but 
```json
{
"rust-analyzer.cargo.features": ["all"],
}
```
was not working. I was getting an error saying there is no feature named "all". After some digging I found the correct API to be. (I got it from #334 and #229)
```json
{
"rust-analyzer.cargo.allFeatures": true,
}
```
Not sure if I am using an older version or not. Posting this PR just in case. Let me know. Thanks
=> chore(README): rust-analyzer.cargo.allFeatures

src/commands.ts
When invoking `rust-analyzer.debug` there can be significant delay.
`debugSingle` will try to build the requested target as part of
generating the executable location.
This change notifies the users of these build steps.
=> Update users on status of incomplete runnables

src/commands.ts
Basically #1048 but in the new style:
=> Show debug runnable build notifications in a window

README.md, coc-rust-analyzer-configurations.json, package.json, src/commands.ts, src/config.ts
With this pull request, you could use [nvim-dap](https://github.com/mfussenegger/nvim-dap) as debug runtime with just a few configuration like below.
Then, you could invoke debugging with nvim-dap through codeLens.
=> feat: add support for using nvim-dap as debug runtime

README.md
`rust-analyzer.completion.autoself.enable` had a line break in its description which offseted part of the desription and also the default value to a new row in the table of configurations
=> remove line break in README.md

src/client.ts, src/commands.ts
Opening docs (rust-analyzer.openDocs) was broken by commit 1410329b4625f3b6b02bb96675ec5313ba0fab25. This commit contains changes preparing for the rust-analyzer "localDocs" feature https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/lsp-extensions.md#local-documentation However, this feature is only activated by specifying the "localDocs" capability. This commits does so in src/client.ts.
To actually make use of the local documentation, the src/commands.ts:openDocs function also needs adjustment. I wrote it such that if a local URI is provided and a corresponding file exists, it is opened.
Otherwise, if a web link is provided, this link is opened.
Note that "vscode.open" would open the local URI in the editor instead of the browser.
Whether local documentation exists depends …
=> feat: enable localDocs

src/commands.ts
Thanks for merging #1261! However, the negation added to the condition of the if statement means that the code only attempts to open local docs if the corresponding file does not exist, which means local docs don't get used.
=> fix: open local docs if they exist

src/commands.ts
The language server provides snippets containing numbered placeholders of the form `${n:placeholder}`, where `n` is positive integer, and `placeholder` some value to insert when inserting the snippet.
This fix addresses values for `n` which contain the digit `0`, such as `10` and `20`, which previously did not get expanded properly.
=> fix: support numeric snippet labels containing '0'

src/client.ts
As in <https://github.com/rust-lang/rust-analyzer/issues/18709>, Rust Analyzer does not report cargo-produced diagnostics on `textDocument/diagnostic` request. Due to the behavior, coc.nvim often resets diagnostics as described in #1276.
Although I think it's Rust Analyzer that should be fixed, I temporary fix the problem by preserving `rustc` diagnostics on the request with `provideDiagnostic()` middleware.
Closes #1276.
=> Preserve rustc diagnostics on textDocument/diagnostic request

README.md, src/commands.ts, src/index.ts, src/lsp_ext.ts
Changed on the rust-analyzer side, this patch reflects that in the extension.
=> fix: rename `syntaxTree` to `viewSyntaxTree`
